### ISSUE TITLE
No longer builds with diesel 0.8

### ISSUE THREAD

**Issue by MoreAxes** [darayus/iron-diesel-middleware#2]
Compiling with diesel 0.8 fails to typecheck. Attaching cargo log. I had a go at fixing this, but it's not clear to me what's wrong; PgConnection satisfies Connection just fine.

```
error[E0277]: the trait bound `diesel::pg::PgConnection: diesel::connection::Connection` is not satisfied
  --> src\lib.rs:19:3
   |
19 |   pub pool: DieselPool,
   |   ^^^^^^^^^^^^^^^^^^^^ trait `diesel::pg::PgConnection: diesel::connection::Connection` not satisfied
   |
   = note: required because of the requirements on the impl of `r2d2::ManageConnection` for `r2d2_diesel::ConnectionManager<diesel::pg::PgConnection>`
   = note: required by `r2d2::Pool`

error[E0277]: the trait bound `diesel::pg::PgConnection: diesel::connection::Connection` is not satisfied
  --> src\lib.rs:22:18
   |
22 | pub struct Value(DieselPool);
   |                  ^^^^^^^^^^^ trait `diesel::pg::PgConnection: diesel::connection::Connection` not satisfied
   |
   = note: required because of the requirements on the impl of `r2d2::ManageConnection` for `r2d2_diesel::ConnectionManager<diesel::pg::PgConnection>`
   = note: required by `r2d2::Pool`

error[E0277]: the trait bound `diesel::pg::PgConnection: diesel::connection::Connection` is not satisfied
  --> src\lib.rs:46:6
   |
46 | impl BeforeMiddleware for DieselMiddleware {
   |      ^^^^^^^^^^^^^^^^ trait `diesel::pg::PgConnection: diesel::connection::Connection` not satisfied
   |
   = note: required because of the requirements on the impl of `r2d2::ManageConnection` for `r2d2_diesel::ConnectionManager<diesel::pg::PgConnection>`
   = note: required because it appears within the type `r2d2::SharedPool<r2d2_diesel::ConnectionManager<diesel::pg::PgConnection>>`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<r2d2::SharedPool<r2d2_diesel::ConnectionManager<diesel::pg::PgConnection>>>`
   = note: required because it appears within the type `r2d2::Pool<r2d2_diesel::ConnectionManager<diesel::pg::PgConnection>>`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<r2d2::Pool<r2d2_diesel::ConnectionManager<diesel::pg::PgConnection>>>`
   = note: required because it appears within the type `DieselMiddleware`
   = note: required by `iron::BeforeMiddleware`

error[E0277]: the trait bound `diesel::pg::PgConnection: diesel::connection::Connection` is not satisfied
  --> src\lib.rs:75:3
   |
75 |   fn db_conn(&self) -> r2d2::PooledConnection<r2d2_diesel::ConnectionManager<PgConnection>>;
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ trait `diesel::pg::PgConnection: diesel::connection::Connection` not satisfied
   |
   = note: required because of the requirements on the impl of `r2d2::ManageConnection` for `r2d2_diesel::ConnectionManager<diesel::pg::PgConnection>`
   = note: required by `r2d2::PooledConnection`

error[E0277]: the trait bound `diesel::pg::PgConnection: diesel::connection::Connection` is not satisfied
  --> src\lib.rs:79:3
   |
79 |   fn db_conn(&self) -> r2d2::PooledConnection<r2d2_diesel::ConnectionManager<PgConnection>> {
   |   ^ trait `diesel::pg::PgConnection: diesel::connection::Connection` not satisfied
   |
   = note: required because of the requirements on the impl of `r2d2::ManageConnection` for `r2d2_diesel::ConnectionManager<diesel::pg::PgConnection>`
   = note: required by `r2d2::PooledConnection`

error: aborting due to 5 previous errors

error: Could not compile `iron_diesel_middleware`.
```

**Comment by darayus** [comment]
I've updated the dependencies and the documentation to the latest versions of diesel, iron, and r2d2. The issue you came across was probably caused by having multiple versions of the same crate - this should be fixed now but please let me know if you still see the same error. Thanks for bringing this to my attention 👍.

**Comment by MoreAxes** [comment]
Thanks for the quick response! Unfortunately, this didn't seem to help. After a `cargo clean`, I attempted to build the example, but it failed with exactly the same error. Building the crate itself appears to work fine, but when I attempt to use it in my application, I get another set of seemingly impossible errors when attempting to link `DieselMiddleware` to my Iron chain:

```
error[E0277]: the trait bound `for<'r, 'r, 'r> idm::DieselMiddleware: std::ops::Fn<(&'r mut iron::Request<'r, 'r>,)>` is not satisfied
  --> src\main.rs:90:9
   |
90 |   chain.link_before(diesel_mw);
   |         ^^^^^^^^^^^ trait `for<'r, 'r, 'r> idm::DieselMiddleware: std::ops::Fn<(&'r mut iron::Request<'r, 'r>,)>` not satisfied
   |
   = note: required because of the requirements on the impl of `iron::BeforeMiddleware` for `idm::DieselMiddleware`

error[E0277]: the trait bound `for<'r, 'r, 'r> idm::DieselMiddleware: std::ops::FnOnce<(&'r mut iron::Request<'r, 'r>,)>` is not satisfied
  --> src\main.rs:90:9
   |
90 |   chain.link_before(diesel_mw);
   |         ^^^^^^^^^^^ trait `for<'r, 'r, 'r> idm::DieselMiddleware: std::ops::FnOnce<(&'r mut iron::Request<'r, 'r>,)>` not satisfied
   |
   = note: required because of the requirements on the impl of `iron::BeforeMiddleware` for `idm::DieselMiddleware`

error: aborting due to 5 previous errors
```
(impossible because, as far as I can tell, `DieselMiddleware` impls `BeforeMiddleware` just fine, so I don't get what the `FnOnce` parts are about)

**Comment by darayus** [comment]
What version is your iron dependency pinned at? I updated the crate to v0.4 which is the latest published version (as far as I can tell). If your iron is at the same version, can you then check that in your `Cargo.lock` file there aren't multiple versions of iron listed. You can quickly get a list of all the version numbers by running the following command:

```bash
egrep "\"iron \d" Cargo.lock
```

**Comment by MoreAxes** [comment]
My checkout of `iron-diesel-middleware` was pinned at 0.3.1, so I've ran `cargo update`, and now the example builds fine. My application indeed had two Iron entries, one with 0.3.1 and the other with 0.4. `cargo update` fixed this as well, and now it builds fine.

Thanks for the help!

**Comment by darayus** [comment]
No worries, glad to hear everything's working now!
